#!/usr/bin/env python3
"""从唯一真源 signatures/ad_signatures.json 生成 adblock_domains.h。

该头文件被 adblock.m 包含，提供 kAdHosts[]（广告域名拦截清单）。
改名单只需编辑 ad_signatures.json 的 ad_endpoints 字段，重新编译
（make / GitHub Actions）即生效，无需改动 Objective-C 代码。

运行：
    python3 generate_domains.py                # 仅 ad_endpoints
    python3 generate_domains.py --include-tracking   # 追加埋点域名
纯标准库实现，Windows / macOS 均可运行。
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
# dylib_src/adblock/ -> 仓库根 (ad-remover/)
SIG_PATH = HERE.parent.parent / "signatures" / "ad_signatures.json"
OUT_PATH = HERE / "adblock_domains.h"


def main() -> int:
    ap = argparse.ArgumentParser(description="为 adblock.m 生成域名清单头文件")
    ap.add_argument("--include-tracking", action="store_true",
                    help="同时把 tracking_endpoints 纳入拦截清单")
    ap.add_argument("--signatures", type=Path, default=SIG_PATH,
                    help="签名库路径（默认 ../../signatures/ad_signatures.json）")
    args = ap.parse_args()

    if not args.signatures.exists():
        print(f"[generate_domains] 错误：找不到签名库 {args.signatures}", file=sys.stderr)
        return 1

    sig = json.loads(args.signatures.read_text(encoding="utf-8"))
    hosts = list(sig.get("ad_endpoints", []))
    if args.include_tracking:
        hosts += list(sig.get("tracking_endpoints", []))

    # 去重并保持顺序
    seen: set[str] = set()
    unique: list[str] = []
    for h in hosts:
        if h not in seen:
            seen.add(h)
            unique.append(h)

    lines = [
        "/* AUTO-GENERATED by generate_domains.py — 请勿手改。 */",
        "/* 唯一真源: signatures/ad_signatures.json 的 ad_endpoints",
        "   （--include-tracking 时追加 tracking_endpoints）。 */",
        "static const char *kAdHosts[] = {",
    ]
    for h in unique:
        lines.append(f'    "{h}",')
    lines.append("    NULL")
    lines.append("};")
    lines.append("")

    OUT_PATH.write_text("\n".join(lines), encoding="utf-8")
    print(f"[generate_domains] 已写入 {OUT_PATH} （{len(unique)} 个域名）")
    return 0


if __name__ == "__main__":
    sys.exit(main())
